<# Bucket F: asdf-cache -- asdf-vm download cache + age-gated stale per-tool installs.
   Cleans:
     %USERPROFILE%\.asdf\downloads                          (raw .tar.gz / .zip download cache, ALWAYS swept)
     %USERPROFILE%\.asdf\installs\<plugin>\<version>        (AGE-GATED -- only installs untouched for >$Days)
     'asdf reshim' is invoked AFTER sweep when CLI is on PATH (rebuilds shim metadata).
   Default $Days = 30. Override with --days N. A per-tool install is a candidate iff:
     (a) its directory's LastWriteTime is older than the cutoff, AND
     (b) it is NOT the active version per `asdf current <plugin>` (asdf may report 'system' or a pinned version).
   SAFE: ~/.asdf/shims (regenerated by reshim), ~/.asdf/plugins (plugin definitions),
         ~/.tool-versions / .tool-versions in any project, the active version of every plugin,
         any install touched within the last $Days days.
   NOTE: asdf is primarily POSIX (bash/zsh) but works under Git Bash / WSL on Windows;
         this helper assumes the on-disk layout exists (~/.asdf), regardless of shell.
#>
param([switch]$DryRun, [switch]$Yes, [int]$Days = 30, [hashtable]$SharedResult)

$here = Split-Path -Parent $MyInvocation.MyCommand.Definition
. (Join-Path $here "_sweep.ps1")

$result = New-CleanResult -Category "asdf-cache" -Label "asdf downloads (always) + stale installs >$Days days (active SAFE)" -Bucket "F"

$asdfRoot = Join-Path (Get-UserProfilePath) ".asdf"
if (-not (Test-Path -LiteralPath $asdfRoot)) {
    $result.Notes += "asdf not present (no $asdfRoot)"
    Set-CleanResultStatus -Result $result -DryRun:$DryRun
    return $result
}

# (1) Always sweep the downloads cache (pure tarball artifacts, asdf re-fetches on demand)
$dlDir = Join-Path $asdfRoot "downloads"
if (Test-Path -LiteralPath $dlDir) {
    Invoke-PathSweep -Path $dlDir -Result $result -DryRun:$DryRun -LogPrefix "asdf/downloads"
} else {
    $result.Notes += "No $dlDir (no downloads to sweep)"
}

# (2) Age-gated installs/<plugin>/<version> walk
$installsDir = Join-Path $asdfRoot "installs"
if (-not (Test-Path -LiteralPath $installsDir)) {
    $result.Notes += "No $installsDir (no per-tool versions installed)"
    Set-CleanResultStatus -Result $result -DryRun:$DryRun
    return $result
}

# Resolve active versions per plugin (best effort -- if asdf is missing, fail safe by skipping NOTHING)
$activeMap = @{}  # key: plugin, value: active version string ('system' allowed)
$asdfCmd = Get-Command "asdf" -ErrorAction SilentlyContinue
if ($null -ne $asdfCmd) {
    try {
        $plugins = @(Get-ChildItem -LiteralPath $installsDir -Directory -Force -ErrorAction SilentlyContinue)
        foreach ($p in $plugins) {
            try {
                # 'asdf current <plugin>' prints e.g. "nodejs          18.19.0     /home/u/.tool-versions"
                $line = (& asdf current $p.Name 2>$null | Select-Object -First 1)
                if (-not [string]::IsNullOrWhiteSpace($line)) {
                    $cols = ($line -split '\s+') | Where-Object { $_ }
                    if ($cols.Count -ge 2) { $activeMap[$p.Name] = $cols[1].Trim() }
                }
            } catch {
                Write-Log "asdf current $($p.Name) failed: $($_.Exception.Message)" -Level "warn"
            }
        }
        $result.Notes += "Active versions resolved for $($activeMap.Count) plugin(s) via 'asdf current'"
    } catch {
        Write-Log "asdf plugin probe failed: $($_.Exception.Message)" -Level "warn"
    }
}

$cutoff = (Get-Date).AddDays(-$Days)
$plugins = @(Get-ChildItem -LiteralPath $installsDir -Directory -Force -ErrorAction SilentlyContinue)
if ($plugins.Count -eq 0) {
    $result.Notes += "No plugins under $installsDir"
    Set-CleanResultStatus -Result $result -DryRun:$DryRun
    return $result
}

$kept    = @()
$removed = @()
foreach ($plugin in $plugins) {
    $active = $activeMap[$plugin.Name]
    $versionDirs = @(Get-ChildItem -LiteralPath $plugin.FullName -Directory -Force -ErrorAction SilentlyContinue)
    foreach ($vd in $versionDirs) {
        # (a) active -- never remove
        if ($active -and $vd.Name -ieq $active) {
            $kept += "$($plugin.Name)/$($vd.Name) (active)"
            continue
        }
        # (b) age gate
        if ($vd.LastWriteTime -ge $cutoff) {
            $kept += "$($plugin.Name)/$($vd.Name) (touched $($vd.LastWriteTime.ToString('yyyy-MM-dd')))"
            continue
        }
        $removed += [pscustomobject]@{ Plugin = $plugin.Name; Dir = $vd }
    }
}

foreach ($k in $kept) { $result.Notes += "KEEP: $k" }

if ($removed.Count -eq 0) {
    $result.Notes += "No stale per-tool installs -- all within $Days-day window or active"
} else {
    foreach ($entry in $removed) {
        $age = [Math]::Round(((Get-Date) - $entry.Dir.LastWriteTime).TotalDays, 0)
        $result.Notes += "STALE candidate: $($entry.Plugin)/$($entry.Dir.Name) (last touched $($entry.Dir.LastWriteTime.ToString('yyyy-MM-dd')), $age days ago)"
        Invoke-PathSweep -Path $entry.Dir.FullName -Result $result -DryRun:$DryRun -LogPrefix "asdf/installs/$($entry.Plugin)/$($entry.Dir.Name)"
    }
}

# (3) Best-effort 'asdf reshim' AFTER sweep (rebuilds shim metadata)
if (-not $DryRun -and $null -ne $asdfCmd) {
    try {
        & asdf reshim 2>$null | Out-Null
        $result.Notes += "Invoked 'asdf reshim' after sweep (shim refresh)"
    } catch {
        Write-Log "asdf reshim failed: $($_.Exception.Message)" -Level "warn"
    }
}

Set-CleanResultStatus -Result $result -DryRun:$DryRun
return $result
